"""fix

Revision ID: 210f22d2e650
Revises: 44fd0148bf9d
Create Date: 2025-05-29 10:57:38.149648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210f22d2e650'
down_revision: Union[str, None] = '44fd0148bf9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'exam_questions', 'questions', ['question_id'], ['id'])
    op.add_column('questions', sa.Column('exam_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'exam_papers', ['exam_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'exam_id')
    op.drop_constraint(None, 'exam_questions', type_='foreignkey')
    # ### end Alembic commands ###
