"""init

Revision ID: 7f8e732980cf
Revises: 05751e578dcd
Create Date: 2025-05-29 09:54:22.260055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '7f8e732980cf'
down_revision: Union[str, None] = [None]
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'question_categories', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['parent_id'],
            ['question_categories.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_question_categories_id'),
                    'question_categories', ['id'],
                    unique=False)
    op.create_table(
        'questions', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('question_type', sa.String(length=50), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('options', sa.JSON(), nullable=True),
        sa.Column('answer', sa.Text(), nullable=False),
        sa.Column('explanation', sa.Text(), nullable=True),
        sa.Column('difficulty', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['category_id'],
            ['question_categories.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.drop_index('ix_exam_results_id', table_name='exam_results')
    op.drop_table('exam_results')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_exams_id', table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams', sa.Column('id', sa.VARCHAR(), nullable=False),
                    sa.Column('title', sa.VARCHAR(), nullable=True),
                    sa.Column('questions', sqlite.JSON(), nullable=True),
                    sa.Column('created_by', sa.VARCHAR(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['created_by'],
                        ['users.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    op.create_index('ix_exams_id', 'exams', ['id'], unique=False)
    op.create_table('users', sa.Column('id', sa.VARCHAR(), nullable=False),
                    sa.Column('email', sa.VARCHAR(), nullable=True),
                    sa.Column('hashed_password', sa.VARCHAR(), nullable=True),
                    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
                    sa.Column('is_superuser', sa.BOOLEAN(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.create_table('exam_results',
                    sa.Column('id', sa.VARCHAR(), nullable=False),
                    sa.Column('exam_id', sa.VARCHAR(), nullable=True),
                    sa.Column('student_id', sa.VARCHAR(), nullable=True),
                    sa.Column('answers', sqlite.JSON(), nullable=True),
                    sa.Column('score', sa.INTEGER(), nullable=True),
                    sa.Column('total_score', sa.INTEGER(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['exam_id'],
                        ['exams.id'],
                    ), sa.ForeignKeyConstraint(
                        ['student_id'],
                        ['users.id'],
                    ), sa.PrimaryKeyConstraint('id'))
    op.create_index('ix_exam_results_id', 'exam_results', ['id'], unique=False)
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_question_categories_id'),
                  table_name='question_categories')
    op.drop_table('question_categories')
    # ### end Alembic commands ###
