"""update

Revision ID: 9962159f360c
Revises: 42e8ce0e3c96
Create Date: 2025-05-29 11:59:31.520719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9962159f360c'
down_revision: Union[str, None] = '42e8ce0e3c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'exam_questions', 'questions', ['question_id'], ['id'])
    op.create_foreign_key(None, 'questions', 'exam_papers', ['exam_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_constraint(None, 'exam_questions', type_='foreignkey')
    # ### end Alembic commands ###
