import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import naive from "naive-ui";
import { createPinia } from "pinia";
import "./style.css";
// import pinia from "pinia";
const app = createApp(App);
app.use(router);
const pinia = createPinia();
app.use(pinia);
app.use(naive);
app.mount("#app");
